// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using health_record_app.Models;

namespace health_record_app.Migrations
{
    [DbContext(typeof(HealthRecordAppContext))]
    partial class HealthRecordAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("health_record_app.Models.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("appointment_date");

                    b.Property<int?>("doctorid");

                    b.Property<int?>("patientid");

                    b.Property<string>("reason");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("health_record_app.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.Property<string>("social_security_number");

                    b.Property<string>("specialty");

                    b.HasKey("id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("health_record_app.Models.Illness", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Illnesses");
                });

            modelBuilder.Entity("health_record_app.Models.Medication", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dosage");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("health_record_app.Models.Patient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date_of_birth");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.Property<char>("middle_initial");

                    b.Property<string>("social_security_number");

                    b.HasKey("id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("health_record_app.Models.Appointment", b =>
                {
                    b.HasOne("health_record_app.Models.Doctor", "doctor")
                        .WithMany()
                        .HasForeignKey("doctorid");

                    b.HasOne("health_record_app.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientid");
                });
#pragma warning restore 612, 618
        }
    }
}
